# Generated by Django 5.0.6 on 2024-06-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_alter_post_content_alter_post_image_like_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_image.png', upload_to='profile_pics/'),
        ),
    ]
