# Generated by Django 5.0.6 on 2024-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
