# Generated by Django 5.0.6 on 2024-06-18 11:30

import instaapp.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0008_remove_post_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='', upload_to='posts/', validators=[instaapp.models.post.validate_feed_file_type]),
            preserve_default=False,
        ),
    ]
