# Generated by Django 5.0.6 on 2024-06-20 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='instaapp.tag'),
        ),
    ]
