# Generated by Django 5.0.6 on 2024-06-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0012_tag_post_mentions_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
