# Generated by Django 5.0.6 on 2024-06-21 06:25

import django.db.models.deletion
import instaapp.models.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0013_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaapp.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instaapp.post'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='instaapp.post'),
        ),
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_reels', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='reels', to='instaapp.tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('user', 'post')},
        ),
        migrations.AddField(
            model_name='comment',
            name='reels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaapp.reels'),
        ),
        migrations.AddField(
            model_name='like',
            name='reels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instaapp.reels'),
        ),
        migrations.AddField(
            model_name='mark',
            name='reels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='instaapp.reels'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post'), ('user', 'reels')},
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('user', 'post'), ('user', 'reels')},
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reels/', validators=[instaapp.models.validators.validate_reels_file_type, instaapp.models.validators.validate_reels_video_length])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='instaapp.reels')),
            ],
        ),
    ]
