# Generated by Django 5.0.6 on 2024-06-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0014_alter_comment_post_alter_like_post_alter_mark_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='instaapp.comment'),
        ),
    ]
