name: Django CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run Linter
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create static and media directories
      run: |
        mkdir -p static
        mkdir -p media
    - name: Collect Static Files
      env:
        DJANGO_SETTINGS_MODULE: instaproject.settings
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DJANGO_DEBUG: 'False'
      run: python manage.py collectstatic --noinput
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-django-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build \
          --build-arg DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
          --build-arg DB_NAME="${{ secrets.DB_NAME }}" \
          --build-arg DB_USER="${{ secrets.DB_USER }}" \
          --build-arg DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          --build-arg DB_HOST="${{ secrets.DB_HOST }}" \
          --build-arg DB_PORT="${{ secrets.DB_PORT }}" \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Test Bastion Connection
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i bastion_key ${USER_NAME}@${BASTION_HOST} 'echo "Bastion connection successful"'
    - name: Check environment variables
      run: |
        echo "BASTION_HOST is set: ${{ secrets.BASTION_HOST != '' }}"
        echo "PRIVATE_HOST is set: ${{ secrets.PRIVATE_HOST != '' }}"
        echo "USER_NAME is set: ${{ secrets.USER_NAME != '' }}"
    - name: Add Github Actions IP to Security group
      run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_BAS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
    - name: Deploy to EC2
      env:
        BASTION_PRIVATE_KEY: ${{ secrets.BASTION_PRIVATE_KEY }}
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        BASTION_HOST: ${{ secrets.BASTION_HOST }}
        PRIVATE_HOST: ${{ secrets.PRIVATE_HOST }}
        USER_NAME: ${{ secrets.USER_NAME }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: my-django-app
        IMAGE_TAG: ${{ github.sha }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        echo "$BASTION_PRIVATE_KEY" > bastion_key && chmod 600 bastion_key
        echo "$EC2_PRIVATE_KEY" > ec2_key && chmod 600 ec2_key
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i bastion_key -J ${USER_NAME}@${BASTION_HOST} ${USER_NAME}@${PRIVATE_HOST} '...'
        "docker login -u AWS -p $(aws ecr get-login-password --region ap-northeast-2) ${ECR_REGISTRY} && \
         docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} && \
         docker stop my-django-app || true && \
         docker rm my-django-app || true && \
         docker run -d --name my-django-app -p 8000:8000 \
         -e DB_NAME='${DB_NAME}' \
         -e DB_USER='${DB_USER}' \
         -e DB_PASSWORD='${DB_PASSWORD}' \
         -e DB_HOST='${DB_HOST}' \
         -e DJANGO_SECRET_KEY='${DJANGO_SECRET_KEY}' \
         -e DJANGO_DEBUG='False' \
         ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} && \
         docker exec my-django-app python manage.py migrate"
    - name: Remove Github Actions IP From Security Group
      run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_BAS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
    - name: Cleanup
      run: |
        rm bastion_key ec2_key
